[main]
title = "빵야 TV"
url = "https://www.bbangyatv.com/main"
entrySelector = "div[class='d-flex flex-wrap v-card v-card--flat v-sheet theme--light'] div[class='schedule-card v-card v-card--flat v-sheet theme--light']"
titleSelector = "h4[class='subtitle-1 twoLineEllipsis font-weight-medium']"
linkSelector = "a"
contentSelector = "div[class='ml-2']"
imageSelector = "div[class='v-image__image v-image__image--cover']"
waitUntil = "networkidle"
onFail = "stale"

[media]
title = "빵야 TV ─ 전체 영상"
url = "https://www.bbangyatv.com/media"
entrySelector = "div[class='px-1 px-md-6 pt-5 pb-0 col-sm-6 col-md-4 col-lg-3 col-12']"
titleSelector = "div.v-card__subtitle.twoLineEllipsis.subtitle-1.font-weight-medium.px-2.py-1"
linkSelector = "a"
imageSelector = "div[class='v-image__image v-image__image--cover']"
waitForSelector = "div[class='px-1 px-md-6 pt-5 pb-0 col-sm-6 col-md-4 col-lg-3 col-12']"
onFail = "stale"
